// ── Helpers de tiempo ────────────────────────────────────────────────────────

export function dayOfYear(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0)
  const diff = date - start + (start.getTimezoneOffset() - date.getTimezoneOffset()) * 60 * 1000
  return Math.floor(diff / (1000 * 60 * 60 * 24))
}

export function weekOfYear(date = new Date()) {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()))
  const dayNum = d.getUTCDay() || 7
  d.setUTCDate(d.getUTCDate() + 4 - dayNum)
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1))
  return Math.ceil(((d - yearStart) / 86400000 + 1) / 7)
}

// ── Conceptos diarios (42 total) ─────────────────────────────────────────────

export const DAILY_CONCEPTS = [
  // ── ESTOICISMO (8) ────────────────────────────────────────────────────────
  {
    id: 1,
    emoji: '🔥',
    category: 'Estoicismo',
    title: 'Amor Fati',
    body: 'Amor Fati, "amar el destino", es la invitación a no solo aceptar lo que ocurre, sino a amarlo profundamente. Nietzsche y los estoicos coincidían en que la grandeza no está en evitar el sufrimiento, sino en transformarlo en combustible. Cada obstáculo, cada fracaso, cada pérdida contiene en sí mismo la semilla de algo mayor si decides mirarlo con esa lente.',
    author: 'Nietzsche / Marco Aurelio',
    apply_today: 'Elige una situación difícil que estés viviendo ahora y escribe en un papel cómo podría ser una oportunidad disfrazada de problema. No para negarlo, sino para verlo desde otro ángulo.',
  },
  {
    id: 2,
    emoji: '💀',
    category: 'Estoicismo',
    title: 'Memento Mori',
    body: 'Memento Mori, "recuerda que morirás", no es un pensamiento oscuro sino una de las herramientas más poderosas de los estoicos para vivir con plenitud. Marco Aurelio la usaba cada mañana para priorizar lo verdaderamente importante. Cuando recuerdas que el tiempo es finito, dejas de malgastarlo en trivialidades y rencores, y comienzas a invertirlo en lo que realmente importa.',
    author: 'Marco Aurelio',
    apply_today: 'Antes de dormir hoy, pregúntate: si este fuera mi último día, ¿qué haría diferente? No para angustiarte, sino para identificar una sola cosa que puedes hacer mañana con más intención.',
  },
  {
    id: 3,
    emoji: '🌧️',
    category: 'Estoicismo',
    title: 'Premeditatio Malorum',
    body: 'La premeditación del mal es la práctica estoica de visualizar con anticipación lo que podría salir mal, no para paralizarse de miedo, sino para reducir su poder. Séneca escribía que el hombre sabio se prepara mentalmente para los golpes de la fortuna antes de que lleguen. Cuando imaginamos la pérdida de algo valioso, aprendemos a apreciarlo con más profundidad en el presente.',
    author: 'Séneca',
    apply_today: 'Tómate 5 minutos para imaginar cómo sería tu día sin una cosa que normalmente das por sentada. Luego, usa ese ejercicio para sentir gratitud genuina por tenerla hoy.',
  },
  {
    id: 4,
    emoji: '⚖️',
    category: 'Estoicismo',
    title: 'Dicotomía del control',
    body: 'Epicteto, que fue esclavo antes de convertirse en filósofo, enseñó que la libertad real no viene del exterior sino de reconocer la distinción fundamental: hay cosas que dependen de nosotros (nuestros juicios, deseos, impulsos) y cosas que no dependen de nosotros (el cuerpo, la reputación, el cargo, la fortuna). La paz interior surge cuando dejamos de gastar energía luchando contra lo que no podemos controlar y dirigimos toda nuestra potencia hacia lo que sí está en nuestras manos.',
    author: 'Epicteto',
    apply_today: 'Haz dos columnas: "Lo que puedo controlar hoy" y "Lo que no puedo controlar hoy". Escribe al menos tres cosas en cada columna y decide conscientemente soltar las de la segunda lista.',
  },
  {
    id: 5,
    emoji: '🌱',
    category: 'Estoicismo',
    title: 'Eudaimonia',
    body: 'Aristóteles llamó eudaimonia al florecimiento humano: no es un estado de placer pasajero sino el resultado de vivir según tus virtudes y tu potencial más profundo. Es la diferencia entre sentirse bien y ser bien. La eudaimonia no se persigue directamente, sino que es el subproducto natural de actuar con excelencia, contribuir a otros y desarrollar sistemáticamente tus capacidades.',
    author: 'Aristóteles',
    apply_today: 'Identifica una virtud que admiras profundamente en otras personas (valentía, generosidad, paciencia) y encuentra una forma concreta de practicarla hoy, aunque sea en un gesto pequeño.',
  },
  {
    id: 6,
    emoji: '⏳',
    category: 'Estoicismo',
    title: 'El momento presente',
    body: 'Marco Aurelio escribía en sus meditaciones privadas que el tiempo es un río de instantes que fluyen y que nunca se repiten. No existe ni el pasado que ya se fue ni el futuro que aún no es; solo existe este momento preciso. La mente que vive en el pasado se deprime; la que vive en el futuro se ansiosa. Solo la mente que habita el presente puede actuar con plena efectividad.',
    author: 'Marco Aurelio',
    apply_today: 'Durante tu próxima comida o caminata, apaga el teléfono y practica estar completamente presente: observa los colores, los sonidos, las sensaciones. Solo por esos minutos, que el presente sea todo.',
  },
  {
    id: 7,
    emoji: '💎',
    category: 'Estoicismo',
    title: 'La virtud como único bien',
    body: 'Para Séneca y los estoicos, la virtud no era solo uno de muchos bienes: era el único bien verdadero. La salud, la riqueza y el placer son "indiferentes" porque pueden existir tanto en el hombre bueno como en el malo. Solo la virtud, la excelencia del carácter, constituye una vida verdaderamente bien vivida. Esto libera al practicante de la ansiedad constante por acumular o proteger bienes externos.',
    author: 'Séneca',
    apply_today: 'Reflexiona sobre una decisión que tomaste recientemente. ¿Fue guiada por lo que parecía conveniente o por lo que era genuinamente correcto? Practica hoy tomar una decisión pequeña exclusivamente desde la virtud.',
  },
  {
    id: 8,
    emoji: '🌌',
    category: 'Estoicismo',
    title: 'El Logos',
    body: 'Los estoicos creían en el Logos, el principio racional que impregna y ordena todo el universo. Cada ser humano contiene una chispa de ese Logos, lo que significa que somos seres racionales por naturaleza y que vivir racionalmente es vivir en armonía con el cosmos entero. Esta visión genera tanto humildad —somos parte de algo inmensamente mayor— como responsabilidad: nuestra razón es sagrada y debe usarse con cuidado.',
    author: 'Epicteto',
    apply_today: 'Cuando enfrentes hoy una situación emocionalmente cargada, detente un momento antes de reaccionar y pregúntate: "¿Qué haría la parte más racional y sabia de mí en este momento?" Actúa desde ahí.',
  },

  // ── PSICOLOGÍA POSITIVA (10) ───────────────────────────────────────────────
  {
    id: 9,
    emoji: '🌊',
    category: 'Psicología positiva',
    title: 'Estado de Flujo',
    body: 'El psicólogo Mihaly Csikszentmihalyi describió el "flow" como el estado óptimo de la experiencia humana: cuando estamos completamente absortos en una actividad que desafía nuestras habilidades sin sobrepasarlas. En ese estado, el tiempo desaparece, el ego se disuelve y la actividad se vuelve intrínsecamente satisfactoria. Es el antídoto natural al aburrimiento y la ansiedad simultáneamente.',
    author: 'Mihaly Csikszentmihalyi',
    apply_today: 'Identifica una tarea que hoy sea lo suficientemente desafiante como para requerirte atención total. Desactiva todas las notificaciones y destina al menos 45 minutos ininterrumpidos a esa tarea. Busca el flujo.',
  },
  {
    id: 10,
    emoji: '🪨',
    category: 'Psicología positiva',
    title: 'Resiliencia',
    body: 'La resiliencia no es la ausencia de sufrimiento ni la capacidad de ignorarlo: es la habilidad de doblarse sin romperse y de encontrar un camino de regreso desde la adversidad. La investigación de Bonanno y otros demuestra que la resiliencia no es un rasgo fijo sino una capacidad que se entrena activamente a través de la reflexión, el apoyo social y la narrativa que construimos sobre lo que nos ocurre.',
    author: 'Psicología contemporánea',
    apply_today: 'Recuerda una situación difícil que hayas superado en el pasado. Escribe en tres oraciones qué aprendiste de ella y cómo te hizo más fuerte. Usa ese recuerdo como evidencia de tu propia resiliencia hoy.',
  },
  {
    id: 11,
    emoji: '💝',
    category: 'Psicología positiva',
    title: 'Autocompasión',
    body: 'Kristin Neff, pionera en la investigación sobre autocompasión, descubrió que la forma en que nos hablamos a nosotros mismos después de un fracaso importa enormemente. La autocompasión no es autoindulgencia ni excusa: es tratarte con la misma amabilidad que darías a un buen amigo en dificultades. Las personas con alta autocompasión son, paradójicamente, más responsables de sus errores porque no les temen tanto.',
    author: 'Kristin Neff',
    apply_today: 'Identifica algo de lo que te hayas criticado duramente esta semana. Escríbelo y luego escribe la respuesta que le darías a un amigo querido que te contara ese mismo problema. Aplícate esa misma respuesta.',
  },
  {
    id: 12,
    emoji: '🧠',
    category: 'Psicología positiva',
    title: 'Neuroplasticidad',
    body: 'Durante décadas se creyó que el cerebro adulto era fijo e inmutable. La neurociencia moderna ha demostrado que el cerebro continúa creando nuevas conexiones neuronales a lo largo de toda la vida, en respuesta a la experiencia y el aprendizaje. Esto significa que ningún patrón de pensamiento, emoción o conducta está tallado en piedra. Lo que practicas se fortalece; lo que abandonas se debilita.',
    author: 'Neurociencia moderna',
    apply_today: 'Aprende algo completamente nuevo hoy, aunque sea pequeño: una palabra en otro idioma, un acorde en guitarra, un dato histórico. Cada experiencia de aprendizaje literalmente cambia la estructura física de tu cerebro.',
  },
  {
    id: 13,
    emoji: '☁️',
    category: 'Psicología positiva',
    title: 'Mindfulness',
    body: 'El mindfulness o atención plena no es vaciar la mente sino observarla sin identificarse con sus contenidos. Jon Kabat-Zinn lo definió como "prestar atención de manera intencional, en el momento presente, sin juzgar". La práctica regular reduce el cortisol, mejora la regulación emocional y aumenta la densidad de materia gris en regiones del cerebro asociadas con la empatía y la toma de decisiones.',
    author: 'Jon Kabat-Zinn',
    apply_today: 'Practica 5 minutos de respiración consciente: inhala contando hasta 4, retén el aire 1 segundo, exhala contando hasta 6. Cuando la mente divague, simplemente regresa a la respiración sin juzgarte.',
  },
  {
    id: 14,
    emoji: '💪',
    category: 'Psicología positiva',
    title: 'Autoeficacia',
    body: 'Albert Bandura acuñó el término "autoeficacia" para describir la creencia en la propia capacidad para ejecutar los comportamientos necesarios para producir resultados específicos. No es confianza en general; es la convicción concreta de que puedes hacer lo que se requiere. Las personas con alta autoeficacia persisten más ante los obstáculos, se recuperan más rápido de los fracasos y establecen metas más desafiantes.',
    author: 'Albert Bandura',
    apply_today: 'Piensa en una habilidad que hayas desarrollado a lo largo del tiempo. Recuerda cómo era al principio y cómo es ahora. Usa esa evidencia concreta para reforzar tu creencia de que puedes desarrollar la habilidad en la que estás trabajando ahora.',
  },
  {
    id: 15,
    emoji: '🙏',
    category: 'Psicología positiva',
    title: 'Gratitud práctica',
    body: 'Robert Emmons, el investigador más citado sobre gratitud, ha demostrado que las personas que llevan un diario de gratitud reportan mayor bienestar subjetivo, menos síntomas físicos, mayor optimismo y más comportamientos de ayuda hacia otros. La gratitud no es ingenua: es el reconocimiento activo de que hay bien en tu vida, que no provino únicamente de ti mismo.',
    author: 'Robert Emmons',
    apply_today: 'Escribe 3 cosas específicas por las que estás agradecido hoy. No uses categorías genéricas ("mi salud") sino detalles concretos ("que hoy amanecí sin dolor y pude caminar al trabajo"). La especificidad amplifica el efecto.',
  },
  {
    id: 16,
    emoji: '🎭',
    category: 'Psicología positiva',
    title: 'Inteligencia emocional',
    body: 'Daniel Goleman popularizó la idea de que la inteligencia emocional, la capacidad de reconocer, comprender y gestionar tanto las propias emociones como las ajenas, predice el éxito en la vida más que el coeficiente intelectual. Las cuatro dimensiones clave son: autoconciencia, autorregulación, conciencia social y gestión de relaciones. Afortunadamente, a diferencia del CI, la IE puede desarrollarse de forma deliberada.',
    author: 'Daniel Goleman',
    apply_today: 'Durante el día, cada vez que sientas una emoción intensa, nómbrala con precisión: en lugar de "estoy mal", di "estoy ansioso" o "estoy frustrado". Nombrar las emociones reduce su intensidad y aumenta tu capacidad de responder en lugar de reaccionar.',
  },
  {
    id: 17,
    emoji: '🔄',
    category: 'Psicología positiva',
    title: 'Identidad basada en hábitos',
    body: 'James Clear propone en "Atomic Habits" que el cambio de conducta más duradero ocurre cuando cambiamos la identidad, no solo el comportamiento. En lugar de decir "quiero correr", dices "soy alguien que corre". Cada hábito que practicas es un voto a favor de la identidad que quieres construir. Pequeñas acciones consistentes son, en realidad, actos de autoafirmación identitaria.',
    author: 'James Clear',
    apply_today: 'Elige una identidad que quieras cultivar (atleta, lector, meditador) y haz hoy el hábito más pequeño posible asociado a ella: aunque sean 2 páginas, 5 minutos o 10 sentadillas. Cada repetición es un voto.',
  },
  {
    id: 18,
    emoji: '😌',
    category: 'Psicología positiva',
    title: 'La paradoja de la felicidad',
    body: 'Barry Schwartz y otros psicólogos han documentado la paradoja de que perseguir directamente la felicidad como objetivo muchas veces la aleja. Las personas más felices no se preguntan constantemente "¿soy feliz?" sino que se absorben en actividades significativas, relaciones profundas y contribuciones a algo mayor que ellas mismas. La felicidad es un subproducto, no una meta.',
    author: 'Barry Schwartz',
    apply_today: 'Identifica una actividad que hagas exclusivamente porque te da sentido, sin importar si te hace "sentir bien" de inmediato. Dedícale tiempo hoy sin medir si estás siendo feliz mientras la haces. Simplemente habítala.',
  },

  // ── FILOSOFÍA ORIENTAL (8) ────────────────────────────────────────────────
  {
    id: 19,
    emoji: '🎯',
    category: 'Filosofía oriental',
    title: 'Ikigai',
    body: 'El ikigai es un concepto japonés que apunta a la razón de ser, el motivo por el que uno se levanta cada mañana. Se encuentra en la intersección de cuatro círculos: lo que amas, lo que haces bien, lo que el mundo necesita y por lo que te pueden pagar. No es un destino que se alcanza sino una dirección que se vive. Los estudios en Okinawa, donde hay una concentración inusual de centenarios, muestran que tener ikigai está asociado a mayor longevidad y menor riesgo cardiovascular.',
    author: 'Tradición japonesa',
    apply_today: 'Dibuja o escribe las cuatro preguntas del ikigai: ¿Qué amo hacer? ¿En qué soy bueno? ¿Qué necesita el mundo? ¿Por qué me pueden pagar? No necesitas respuestas perfectas; el ejercicio es comenzar a hacerte las preguntas correctas.',
  },
  {
    id: 20,
    emoji: '🍂',
    category: 'Filosofía oriental',
    title: 'Wabi-Sabi',
    body: 'El wabi-sabi es la estética japonesa que encuentra belleza en lo incompleto, lo impermanente y lo imperfecto. Una taza rota reparada con oro (kintsugi) es más hermosa que una taza perfecta porque lleva visible su historia. Aplicado a la vida, wabi-sabi invita a dejar de buscar la perfección imposible y a encontrar valor en lo inacabado, en las cicatrices, en la asimetría de lo real.',
    author: 'Estética japonesa',
    apply_today: 'Mira algo en tu vida que consideras imperfecto: un rasgo físico, un proyecto inacabado, una relación complicada. Intenta verlo con ojos wabi-sabi: ¿qué historia única cuenta esa imperfección? ¿Qué valor contiene?',
  },
  {
    id: 21,
    emoji: '🌊',
    category: 'Filosofía oriental',
    title: 'Wu Wei',
    body: 'Wu wei es el principio taoísta del "no-esfuerzo" o "acción sin forzar". No significa pasividad sino actuar en armonía con la naturaleza de las cosas, como el agua que rodea los obstáculos en lugar de chocar con ellos. Lao-Tse enseñaba que el gobernante más hábil es el que gobierna sin que los ciudadanos sientan que están siendo gobernados. El esfuerzo excesivo, la rigidez y el control total son siempre contraproducentes.',
    author: 'Lao-Tse / Taoísmo',
    apply_today: 'Identifica una situación en tu vida donde estás forzando demasiado un resultado. Practica hoy el wu wei: da un paso atrás, reduce la presión que ejerces y observa si la situación se mueve más naturalmente sin tu fuerza.',
  },
  {
    id: 22,
    emoji: '🏯',
    category: 'Filosofía oriental',
    title: 'Mushin',
    body: 'Mushin, literalmente "mente sin mente", es el estado zen del guerrero que actúa sin la interferencia del pensamiento consciente o la emoción. No es ausencia de pensamiento sino fluidez: la mente es tan clara que la acción y la intención son una sola cosa. Los maestros de artes marciales lo describían como el estado donde el cuerpo sabe lo que debe hacer antes de que el ego intervenga para obstaculizarlo.',
    author: 'Zen / Artes marciales japonesas',
    apply_today: 'Durante tu entrenamiento de hoy, practica el mushin: en lugar de pensar "¿lo estoy haciendo bien?", simplemente muévete. Confía en lo que tu cuerpo ya sabe. Observa cómo la calidad de tu movimiento cambia cuando el crítico interno se calla.',
  },
  {
    id: 23,
    emoji: '🌸',
    category: 'Filosofía oriental',
    title: 'Anicca',
    body: 'Anicca, la impermanencia, es una de las tres marcas de la existencia en el budismo. Todo cambia: los pensamientos, las emociones, los cuerpos, las relaciones, los imperios. Lo que genera sufrimiento no es el cambio en sí sino nuestra resistencia a él, nuestra insistencia en aferrar lo agradable y rechazar lo desagradable. Comprender anicca no produce nihilismo sino una especie de libertad: si todo pasa, no hay razón para aferrarse tan fuertemente.',
    author: 'Budismo theravada',
    apply_today: 'Cuando hoy sientas una emoción intensa, ya sea placentera o dolorosa, practica observarla diciendo internamente: "Esto también pasará." No para descartarla, sino para relacionarte con ella con más ligereza y menos miedo.',
  },
  {
    id: 24,
    emoji: '📈',
    category: 'Filosofía oriental',
    title: 'Kaizen',
    body: 'Kaizen, que significa "mejora continua" en japonés, fue el principio filosófico detrás de la transformación de la industria japonesa en el siglo XX. Su idea central es radical en su simplicidad: pequeñas mejoras consistentes, acumuladas en el tiempo, producen resultados extraordinarios. No la perfección inmediata sino la progresión deliberada. Toyota lo aplicó a la manufactura; tú puedes aplicarlo a cualquier área de tu vida.',
    author: 'Filosofía japonesa / Toyota',
    apply_today: 'Elige una habilidad o hábito que quieras mejorar. Pregúntate: ¿qué sería un 1% mejor que ayer? No el 100% mejor, no la versión perfecta: solo el 1% más. Hazlo hoy.',
  },
  {
    id: 25,
    emoji: '⬜',
    category: 'Filosofía oriental',
    title: 'Ma',
    body: 'Ma es el concepto japonés del espacio vacío y la pausa, que no son ausencias sino presencias. En la música, el ma es el silencio entre las notas que les da significado. En la arquitectura, es el espacio vacío que da función a la habitación. Aplicado a la vida, ma nos invita a valorar el descanso, las pausas y los momentos sin agenda no como interrupciones de la vida productiva sino como partes esenciales de ella.',
    author: 'Estética japonesa',
    apply_today: 'Reserva 15 minutos hoy para no hacer nada: sin teléfono, sin música, sin agenda. Solo siéntate con el vacío. Este espacio es ma, y es tan necesario como cualquier actividad que hagas.',
  },
  {
    id: 26,
    emoji: '🌅',
    category: 'Filosofía oriental',
    title: 'Mono no Aware',
    body: 'Mono no aware es la conciencia agridulce de la transitoriedad de las cosas. Los japoneses lo celebran en el hanami, la contemplación de los cerezos en flor, que son hermosos precisamente porque duran tan poco. No es tristeza pura sino una sensibilidad exquisita hacia la belleza fugaz, que genera tanto melancolía como gratitud. Es aprender a amar las cosas porque se van, no a pesar de que se vayan.',
    author: 'Estética japonesa clásica',
    apply_today: 'Observa algo hoy que sea temporario: una conversación, un atardecer, el estado físico de alguien que amas. Permite que su carácter transitorio no te entristezca sino que intensifique tu presencia con ello.',
  },

  // ── NEUROCIENCIA APLICADA (8) ─────────────────────────────────────────────
  {
    id: 27,
    emoji: '🔬',
    category: 'Neurociencia aplicada',
    title: 'Dopamina y motivación',
    body: 'La dopamina no es simplemente el "neurotransmisor del placer" como se la suele llamar: es el neurotransmisor del deseo y la anticipación. Tu cerebro libera dopamina más intensamente cuando anticipa una recompensa que cuando la recibe. Esto explica por qué los objetivos a largo plazo deben descomponerse en microrecompensas frecuentes: tu sistema dopaminérgico necesita señales regulares de progreso para mantenerse motivado.',
    author: 'Robert Sapolsky / Neurociencia',
    apply_today: 'Divide una meta grande que tengas en 5 pasos pequeños y específicos. Marca el primero como completado hoy, aunque sea simbólico. La dopamina que libera ese pequeño "check" es real y te impulsa hacia el siguiente.',
  },
  {
    id: 28,
    emoji: '🌡️',
    category: 'Neurociencia aplicada',
    title: 'Cortisol y estrés',
    body: 'El cortisol, la principal hormona del estrés, fue diseñado para respuestas cortas y adaptativas: el tigre que te persigue. El problema moderno es el estrés crónico, que mantiene el cortisol elevado de forma sostenida, suprimiendo el sistema inmune, alterando el sueño y reduciendo la capacidad cognitiva. La ciencia muestra que respiración profunda, ejercicio físico y conexión social son los reguladores más efectivos.',
    author: 'Psicofisiología del estrés',
    apply_today: 'Prueba la respiración 4-7-8 cuando sientas tensión hoy: inhala 4 segundos, retén 7, exhala 8. Repite 4 veces. Este patrón activa el nervio vago y reduce el cortisol en minutos.',
  },
  {
    id: 29,
    emoji: '🧘',
    category: 'Neurociencia aplicada',
    title: 'El sistema nervioso parasimpático',
    body: 'El sistema nervioso autónomo tiene dos modos principales: el simpático ("lucha o huida") y el parasimpático ("descansa y digiere"). En el mundo moderno, muchas personas viven en activación simpática crónica. El sistema parasimpático, activado principalmente por la respiración lenta, el contacto físico, la naturaleza y la meditación, es el sistema de la recuperación, la creatividad y la conexión social.',
    author: 'Neurobiología',
    apply_today: 'Activa tu sistema parasimpático hoy de forma intencional: da un paseo de 10 minutos sin teléfono, practica 5 minutos de respiración diafragmática, o simplemente siéntate al sol. Tu sistema nervioso te lo agradecerá.',
  },
  {
    id: 30,
    emoji: '🔁',
    category: 'Neurociencia aplicada',
    title: 'Hábitos neurológicos',
    body: 'Charles Duhigg, basándose en investigaciones del MIT, popularizó el modelo neurológico del hábito: un bucle compuesto por señal, rutina y recompensa. El cerebro aprende a ejecutar las rutinas automáticamente cuando detecta la señal, liberando recursos cognitivos. Para cambiar un hábito, no se elimina la señal ni se suprime la recompensa: se reemplaza la rutina del medio manteniendo los extremos del bucle.',
    author: 'Charles Duhigg / MIT',
    apply_today: 'Identifica un hábito que quieras cambiar. Escribe: ¿cuál es la señal que lo desencadena? ¿cuál es la recompensa que busca? Luego diseña una rutina alternativa que use la misma señal y entregue una recompensa similar.',
  },
  {
    id: 31,
    emoji: '⚡',
    category: 'Neurociencia aplicada',
    title: 'Neuroplasticidad hebbiana',
    body: 'Donald Hebb enunció el principio que define la neuroplasticidad: "Las neuronas que disparan juntas se conectan." Cada vez que practicas un pensamiento, una emoción o una habilidad, las conexiones neuronales que la sostienen se fortalecen. Cada vez que dejas de practicar algo, esas conexiones se debilitan. Esto convierte cada momento en una elección sobre qué versión de ti mismo estás construyendo o erosionando.',
    author: 'Donald Hebb / Neurociencia',
    apply_today: 'Elige una respuesta emocional o un patrón de pensamiento que quieras fortalecer (como la calma ante la presión). Busca hoy una situación donde puedas practicar deliberadamente esa respuesta. Cada práctica literalmente cambia tu cerebro.',
  },
  {
    id: 32,
    emoji: '🌈',
    category: 'Neurociencia aplicada',
    title: 'Serotonina y bienestar',
    body: 'La serotonina es el neurotransmisor asociado a la calma, la satisfacción y el bienestar duradero, a diferencia de la dopamina que es más asociada a la excitación y el deseo. Los niveles de serotonina se elevan con la luz solar, el ejercicio físico, la alimentación rica en triptófano (pavo, nueces, plátano), las relaciones sociales positivas y los recuerdos de logros pasados.',
    author: 'Neurobiología del bienestar',
    apply_today: 'Haz algo hoy que eleve tu serotonina de forma natural: sal al sol 15 minutos, haz ejercicio, come algo rico en triptófano, o lee una lista de logros personales pasados que te haga sentir orgullo genuino.',
  },
  {
    id: 33,
    emoji: '💭',
    category: 'Neurociencia aplicada',
    title: 'La red neuronal por defecto',
    body: 'La red neuronal por defecto (DMN) es el sistema que se activa cuando tu mente "divaga": cuando no estás enfocado en una tarea externa sino en ensoñaciones, reflexiones sobre uno mismo y proyección al futuro. Lejos de ser una pérdida de tiempo, la DMN es esencial para la creatividad, la consolidación de la memoria y la cognición social. El problema es que en la era de las notificaciones, raramente se le permite activarse.',
    author: 'Marcus Raichle / Neurociencia',
    apply_today: 'Date 20 minutos de tiempo sin estructura hoy: sin pantalla, sin agenda. Deja que tu mente divague libremente. Este tiempo de "ensoñación" activa tu creatividad y consolida los aprendizajes del día.',
  },
  {
    id: 34,
    emoji: '❤️',
    category: 'Neurociencia aplicada',
    title: 'Oxitocina',
    body: 'La oxitocina, llamada popularmente "la hormona del amor o la conexión", se libera durante el contacto físico, la mirada sostenida, la confianza y los momentos de vulnerabilidad compartida. No solo fortalece los vínculos: reduce la ansiedad, baja la presión arterial y aumenta la confianza. Los estudios muestran que incluso recordar con cariño a alguien querido eleva los niveles de oxitocina.',
    author: 'Paul Zak / Neurociencia social',
    apply_today: 'Conéctate genuinamente con alguien hoy: un abrazo real, una conversación sin teléfono, un mensaje pensado para alguien que valoras. No por obligación social sino por el bien demostrado de la conexión humana.',
  },

  // ── FILOSOFÍA PRÁCTICA / EXISTENCIAL (8) ─────────────────────────────────
  {
    id: 35,
    emoji: '🕯️',
    category: 'Filosofía existencial',
    title: 'Logoterapia',
    body: 'Viktor Frankl sobrevivió cuatro campos de concentración nazis y de esa experiencia límite extrajo su mayor insight: que el ser humano puede soportar casi cualquier cómo si tiene un por qué. La logoterapia, la tercera escuela vienesa de psicoterapia, propone que la búsqueda de sentido es la motivación primaria del ser humano, más fundamental que el placer (Freud) o el poder (Adler). El sentido no se inventa: se descubre.',
    author: 'Viktor Frankl',
    apply_today: 'Escribe una respuesta breve a esta pregunta: ¿Para qué hago lo que hago? No el qué ni el cómo, sino el para qué más profundo. Si no tienes una respuesta clara, el ejercicio es tomarte el día para comenzar a buscarla.',
  },
  {
    id: 36,
    emoji: '🎭',
    category: 'Filosofía existencial',
    title: 'La autenticidad',
    body: 'Para Jean-Paul Sartre, "la existencia precede a la esencia": no nacemos con una naturaleza fija que debemos descubrir, sino que nos creamos a nosotros mismos a través de nuestras elecciones. La mala fe (mauvaise foi) es cuando fingimos que no tenemos elección, cuando seguimos el rol social sin cuestionarlo. La autenticidad es la valentía de elegir conscientemente quién ser, sabiendo que esa elección tiene un peso existencial real.',
    author: 'Jean-Paul Sartre',
    apply_today: 'Identifica hoy una cosa que estás haciendo "porque siempre lo hice así" o "porque se supone que debo". Pregúntate si lo elegirías si empezaras desde cero. No necesitas cambiarla hoy: solo mírala con ojos de elección libre.',
  },
  {
    id: 37,
    emoji: '🪞',
    category: 'Filosofía existencial',
    title: 'El cuidado de sí',
    body: 'Michel Foucault estudió las "técnicas del yo" en las culturas griega y romana: prácticas deliberadas a través de las cuales las personas se transformaban a sí mismas para alcanzar un cierto estado de felicidad, pureza o sabiduría. El cuidado de sí no es narcisismo; es la disciplina interior de atender el propio cuerpo, mente y espíritu como condición previa para relacionarse bien con otros y con el mundo.',
    author: 'Michel Foucault',
    apply_today: 'Elige hoy una "técnica del yo": puede ser escribir en un diario, hacer ejercicio con atención plena, meditar, o simplemente preparar una comida nutritiva con cuidado. Hazlo como un acto de autorespeto, no de obligación.',
  },
  {
    id: 38,
    emoji: '🌺',
    category: 'Filosofía existencial',
    title: 'El arte de vivir',
    body: 'Epicuro, frecuentemente malinterpretado como hedonista, en realidad enseñaba una filosofía de placer sutil y duradero sobre el placer intenso y breve. Consideraba que los pilares de la buena vida eran la amistad, la filosofía, la moderación y la ausencia de miedo. Su jardín en Atenas era una comunidad de personas dedicadas a vivir bien, no lujosamente. La felicidad epicúrea es accesible a casi todos porque depende de cosas simples y estables.',
    author: 'Epicuro',
    apply_today: 'Practica el placer epicúreo hoy: una conversación profunda con alguien que valoras, una comida simple disfrutada con atención, o tiempo en la naturaleza. Sin pantallas, sin comparaciones, sin exceso. Solo la cosa simple vivida bien.',
  },
  {
    id: 39,
    emoji: '🎨',
    category: 'Filosofía existencial',
    title: 'Indiferencia creativa',
    body: 'La Gestalt terapéutica propone el concepto de "indiferencia creativa" como el estado de contacto neutral con la realidad antes de cualquier juicio o categorización. No es apatía sino apertura: la capacidad de ver lo que está pasando realmente, sin las distorsiones de nuestras expectativas, deseos o miedos. Desde esa claridad neutral, la respuesta más creativa y adecuada surge naturalmente.',
    author: 'Fritz Perls / Terapia Gestalt',
    apply_today: 'Cuando enfrentes hoy un conflicto o una situación difícil, practica 2 minutos de "indiferencia creativa": describe la situación tan objetivamente como puedas, sin adjetivos que impliquen juicio. Solo los hechos. Observa cómo cambia tu perspectiva.',
  },
  {
    id: 40,
    emoji: '🌱',
    category: 'Filosofía existencial',
    title: 'Shoshin: mente de principiante',
    body: 'En el Zen, shoshin es la mente del principiante: la actitud de apertura, curiosidad y ausencia de prejuicios con que un novato se acerca a algo por primera vez. Shunryu Suzuki lo resumió así: "En la mente del principiante hay muchas posibilidades, pero en la mente del experto hay pocas." La paradoja es que la mayor expertise a menudo destruye la capacidad de seguir aprendiendo, porque el experto cree que ya sabe.',
    author: 'Shunryu Suzuki / Zen',
    apply_today: 'Elige algo que creas conocer muy bien, ya sea una persona, una actividad o un tema. Hoy, acércate a ello como si fuera la primera vez. Haz al menos una pregunta que normalmente no harías porque "ya sabes la respuesta".',
  },
  {
    id: 41,
    emoji: '🎯',
    category: 'Filosofía existencial',
    title: 'Deep Work',
    body: 'Cal Newport define el "deep work" como el estado de concentración sin distracciones en tareas cognitivamente exigentes que llevan tus habilidades al límite y crean nuevo valor. En contraste, el "shallow work" (correos, reuniones, redes sociales) es fácilmente replicable y genera poco valor profundo. Newport argumenta que la capacidad de hacer deep work es una de las habilidades más valiosas y escasas de la economía del conocimiento.',
    author: 'Cal Newport',
    apply_today: 'Programa un bloque de deep work hoy: al menos 90 minutos sin interrupciones, sin teléfono, sin notificaciones, dedicados a la tarea más importante y exigente de tu día. Trata ese bloque como una cita inalienable contigo mismo.',
  },
  {
    id: 42,
    emoji: '🐢',
    category: 'Filosofía existencial',
    title: 'Slow Living',
    body: 'El movimiento slow living surge como respuesta a la aceleración frenética de la vida moderna. No propone hacer menos sino hacer cada cosa con más intención y presencia. La velocidad no es virtud: muchas veces la prisa nos hace eficientes en cosas que no deberían hacerse en absoluto. Vivir despacio es elegir con cuidado a qué das tu tiempo, energía y atención, los recursos más no renovables que tienes.',
    author: 'Movimiento slow / Carl Honoré',
    apply_today: 'Elige una actividad que normalmente haces apresuradamente (comer, ducharte, caminar al trabajo) y hazla hoy el doble de lento. No como pérdida de tiempo sino como experimento de presencia. Nota qué cambia en tu experiencia.',
  },
]

// ── Libros semanales (28 total) ───────────────────────────────────────────────

export const WEEKLY_BOOKS = [
  {
    id: 1,
    emoji: '📖',
    title: 'El hombre en busca de sentido',
    author: 'Viktor Frankl',
    year: 1946,
    genre: 'Psicología / Autobiografía',
    tagline: 'El testimonio más poderoso sobre la búsqueda de sentido en condiciones límite',
    why: 'Frankl sobrevivió Auschwitz y de esa experiencia extrajo una teoría completa sobre la motivación humana. Para quien trabaja en construir disciplina y propósito, este libro ofrece perspectiva indestructible: si hay sentido, cualquier esfuerzo es sostenible.',
    open_library_key: null,
  },
  {
    id: 2,
    emoji: '📜',
    title: 'Meditaciones',
    author: 'Marco Aurelio',
    year: 180,
    genre: 'Filosofía / Estoicismo',
    tagline: 'Las notas privadas de un emperador que se exigía más que a nadie',
    why: 'Nunca escrito para publicarse, este diario personal del emperador Marco Aurelio es un modelo incomparable de autoexigencia y reflexión filosófica aplicada a la vida cotidiana. Cada entrada es un recordatorio de que la virtud se practica, no se declara.',
    open_library_key: null,
  },
  {
    id: 3,
    emoji: '⚗️',
    title: 'El alquimista',
    author: 'Paulo Coelho',
    year: 1988,
    genre: 'Novela filosófica',
    tagline: 'La parábola más vendida sobre seguir tu leyenda personal',
    why: 'Una fábula sobre el coraje de perseguir el propio camino cuando el mundo te invita a quedarte quieto. Para quienes dudan si el esfuerzo de la disciplina personal vale la pena, este libro recuerda que el tesoro está al final del camino, no antes de empezarlo.',
    open_library_key: null,
  },
  {
    id: 4,
    emoji: '🌊',
    title: 'Fluir (Flow)',
    author: 'Mihaly Csikszentmihalyi',
    year: 1990,
    genre: 'Psicología positiva',
    tagline: 'La psicología de la experiencia óptima',
    why: 'Csikszentmihalyi pasó décadas estudiando cuándo las personas se sienten más vivas y comprometidas. El resultado es una guía práctica para diseñar actividades que generen el estado de flujo, el antídoto científico al aburrimiento y la ansiedad.',
    open_library_key: null,
  },
  {
    id: 5,
    emoji: '⏰',
    title: 'El poder del ahora',
    author: 'Eckhart Tolle',
    year: 1997,
    genre: 'Espiritualidad / Psicología',
    tagline: 'Una guía hacia la iluminación espiritual a través del presente',
    why: 'Tolle propone que casi todo sufrimiento humano proviene de vivir mentalmente en el pasado o el futuro. Para quien practica disciplina física y mental, este libro ofrece una dimensión complementaria: la disciplina de habitar el presente.',
    open_library_key: null,
  },
  {
    id: 6,
    emoji: '🤝',
    title: 'Los cuatro acuerdos',
    author: 'Miguel Ruiz',
    year: 1997,
    genre: 'Espiritualidad / Filosofía tolteca',
    tagline: 'Un código de conducta basado en la sabiduría tolteca ancestral',
    why: 'Cuatro principios simples pero profundamente difíciles de practicar: sé impecable con tus palabras, no te tomes nada personal, no supongas, y haz siempre lo máximo que puedas. Un manual minimalista para la integridad personal.',
    open_library_key: null,
  },
  {
    id: 7,
    emoji: '🛡️',
    title: 'Daring Greatly',
    author: 'Brené Brown',
    year: 2012,
    genre: 'Psicología / Autodesarrollo',
    tagline: 'Cómo el coraje de ser vulnerable transforma la forma en que vivimos',
    why: 'Brown demuestra con investigación empírica que la vulnerabilidad no es debilidad sino el origen de la creatividad, la conexión y el cambio. Para quien busca construir fortaleza real, este libro redefine lo que significa ser valiente.',
    open_library_key: null,
  },
  {
    id: 8,
    emoji: '⚛️',
    title: 'Atomic Habits',
    author: 'James Clear',
    year: 2018,
    genre: 'Psicología / Hábitos',
    tagline: 'Un método probado para construir buenos hábitos y eliminar los malos',
    why: 'El marco más práctico y neurocientíficamente fundamentado para entender cómo funcionan los hábitos y cómo cambiarlos. Esencial para cualquiera que trabaja en disciplina y mejora continua: las pequeñas acciones son los votos para la identidad que quieres construir.',
    open_library_key: null,
  },
  {
    id: 9,
    emoji: '🌹',
    title: 'Veinte poemas de amor y una canción desesperada',
    author: 'Pablo Neruda',
    year: 1924,
    genre: 'Poesía',
    tagline: 'Los poemas de amor más leídos en lengua española',
    why: 'La poesía de Neruda no es decoración: es entrenamiento emocional. Leer estos poemas desarrolla la capacidad de nombrar lo que se siente, y esa capacidad, la de la inteligencia emocional verbal, está directamente correlacionada con el bienestar psicológico.',
    open_library_key: null,
  },
  {
    id: 10,
    emoji: '🏔️',
    title: 'Siddhartha',
    author: 'Hermann Hesse',
    year: 1922,
    genre: 'Novela filosófica',
    tagline: 'El viaje de un alma hacia la sabiduría a través de la experiencia',
    why: 'La búsqueda de Siddhartha es la búsqueda de cualquier persona que no quiere vivir solo en la superficie. Hesse muestra que la sabiduría no se enseña sino que se vive, y que los atajos espirituales no existen, solo el camino.',
    open_library_key: null,
  },
  {
    id: 11,
    emoji: '✉️',
    title: 'Cartas a Lucilio',
    author: 'Séneca',
    year: 65,
    genre: 'Filosofía / Estoicismo',
    tagline: 'Las cartas más sabias que un filósofo escribió a su discípulo',
    why: 'Escritas al final de su vida, estas cartas son el testamento filosófico de Séneca: consejos prácticos, profundamente humanos, sobre el tiempo, la muerte, la amistad y la virtud. Una lectura que mejora con cada relectura.',
    open_library_key: null,
  },
  {
    id: 12,
    emoji: '🌊',
    title: 'La Odisea',
    author: 'Homero',
    year: -800,
    genre: 'Literatura épica',
    tagline: 'El arquetipo de todos los viajes de regreso a uno mismo',
    why: 'Odiseo es el modelo del ser humano que no se rinde ante ningún obstáculo, que usa tanto la fuerza como la astucia, y que mantiene su identidad incluso cuando el mundo conspira para hacerlo olvidar quién es. Una lectura que fortalece el carácter.',
    open_library_key: null,
  },
  {
    id: 13,
    emoji: '🌹',
    title: 'El principito',
    author: 'Antoine de Saint-Exupéry',
    year: 1943,
    genre: 'Literatura / Filosofía',
    tagline: 'El cuento más profundo disfrazado de libro para niños',
    why: 'Detrás de la historia aparentemente simple hay una crítica devastadora a los adultos que olvidan lo esencial: la amistad, la belleza, la responsabilidad hacia lo que amamos. Un libro que reorienta las prioridades con una gentileza única.',
    open_library_key: null,
  },
  {
    id: 14,
    emoji: '☯️',
    title: 'Tao Te Ching',
    author: 'Lao-Tse',
    year: -500,
    genre: 'Filosofía / Espiritualidad',
    tagline: 'El texto fundacional del taoísmo en 81 breves capítulos',
    why: 'Difícilmente hay otro libro de 5000 palabras que contenga más sabiduría por párrafo. Para quien tiende al exceso de esfuerzo y control, el Tao Te Ching ofrece el equilibrio opuesto: la potencia del wu wei, la fortaleza de la suavidad.',
    open_library_key: null,
  },
  {
    id: 15,
    emoji: '🦴',
    title: 'Sapiens: de animales a dioses',
    author: 'Yuval Noah Harari',
    year: 2011,
    genre: 'Historia / Ensayo',
    tagline: 'La historia de la humanidad que cambia la forma en que te ves a ti mismo',
    why: 'Comprender la historia de tu especie en su totalidad transforma la perspectiva con la que enfrentas tus propios desafíos. Harari proporciona el contexto más amplio posible para entender por qué somos como somos, y por qué podríamos ser diferentes.',
    open_library_key: null,
  },
  {
    id: 16,
    emoji: '🎨',
    title: 'El camino del artista',
    author: 'Julia Cameron',
    year: 1992,
    genre: 'Creatividad / Autodesarrollo',
    tagline: 'Un curso espiritual de doce semanas para recuperar la creatividad',
    why: 'La creatividad no es un talento exclusivo de los artistas: es la capacidad fundamental de crear tu propia vida. Cameron ofrece herramientas prácticas (las páginas matutinas, las citas del artista) para desbloquear esa creatividad que la vida cotidiana suele enterrar.',
    open_library_key: null,
  },
  {
    id: 17,
    emoji: '🔥',
    title: 'Can\'t Hurt Me',
    author: 'David Goggins',
    year: 2018,
    genre: 'Autobiografía / Motivación',
    tagline: 'La historia más brutal sobre lo que la mente humana puede lograr',
    why: 'Goggins pasó de la obesidad y el abuso a convertirse en el Navy SEAL más reconocido y completar las pruebas de resistencia más duras del mundo. Su historia no es para todos, pero su concepto del "callus mental" (callosidad mental) es una herramienta poderosa.',
    open_library_key: null,
  },
  {
    id: 18,
    emoji: '🧬',
    title: 'El cerebro que se cambia a sí mismo',
    author: 'Norman Doidge',
    year: 2007,
    genre: 'Neurociencia / Divulgación',
    tagline: 'Historias de triunfo personal del campo de la neuroplasticidad',
    why: 'Doidge recopila casos extraordinarios de personas que literalmente reorganizaron su cerebro después de daños severos o limitaciones profundas. Para quien trabaja en cambio personal, este libro ofrece evidencia científica de que la transformación es siempre posible.',
    open_library_key: null,
  },
  {
    id: 19,
    emoji: '🏛️',
    title: 'Discursos',
    author: 'Epicteto',
    year: 108,
    genre: 'Filosofía / Estoicismo',
    tagline: 'Las enseñanzas del esclavo que se convirtió en el filósofo más libre',
    why: 'Epicteto enseñó desde la esclavitud que la libertad interior es la única real. Sus discursos son directos, a veces incómodos, y siempre apuntan a la misma verdad: tú controlas cómo respondes a cualquier cosa que te ocurra.',
    open_library_key: null,
  },
  {
    id: 20,
    emoji: '🌙',
    title: 'La insoportable levedad del ser',
    author: 'Milan Kundera',
    year: 1984,
    genre: 'Novela filosófica',
    tagline: 'Una meditación sobre el amor, la identidad y el peso de las elecciones',
    why: 'Kundera explora con profundidad literaria la paradoja entre el deseo de ligereza y el peso inevitable de las elecciones significativas. Para quien trabaja en construir una vida con sentido, este libro ofrece belleza intelectual y preguntas que permanecen.',
    open_library_key: null,
  },
  {
    id: 21,
    emoji: '🕊️',
    title: 'El monje que vendió su Ferrari',
    author: 'Robin Sharma',
    year: 1997,
    genre: 'Autodesarrollo / Fábula',
    tagline: 'Una fábula espiritual sobre cumplir tus sueños y alcanzar tu destino',
    why: 'A través de una fábula accesible, Sharma transmite principios de autodisciplina, gestión del tiempo y claridad de propósito de forma memorable. Una lectura ideal para comenzar o renovar un camino de desarrollo personal.',
    open_library_key: null,
  },
  {
    id: 22,
    emoji: '🧘',
    title: 'Wherever You Go, There You Are',
    author: 'Jon Kabat-Zinn',
    year: 1994,
    genre: 'Mindfulness / Espiritualidad',
    tagline: 'La guía definitiva al mindfulness en la vida cotidiana',
    why: 'Kabat-Zinn, creador del programa MBSR (Reducción de estrés basada en mindfulness), ofrece una introducción accesible y profunda a la práctica de la atención plena. Para quien entrena el cuerpo, este libro es el complemento para entrenar la mente.',
    open_library_key: null,
  },
  {
    id: 23,
    emoji: '🦁',
    title: 'El coraje de ser',
    author: 'Paul Tillich',
    year: 1952,
    genre: 'Filosofía / Teología',
    tagline: 'Un análisis profundo de la ansiedad y el coraje existencial',
    why: 'Tillich examina el coraje no como ausencia de miedo sino como la afirmación del ser a pesar de la amenaza del no-ser. Una lectura exigente que profundiza la comprensión de por qué la disciplina y la persistencia son actos de valentía fundamental.',
    open_library_key: null,
  },
  {
    id: 24,
    emoji: '🌺',
    title: 'La vida que florece',
    author: 'Martin Seligman',
    year: 2011,
    genre: 'Psicología positiva',
    tagline: 'El padre de la psicología positiva presenta su modelo PERMA del bienestar',
    why: 'Seligman sintetiza décadas de investigación sobre lo que constituye el florecimiento humano: emociones positivas, compromiso, relaciones, sentido y logro. Un mapa científico y práctico hacia una vida bien vivida.',
    open_library_key: null,
  },
  {
    id: 25,
    emoji: '🔮',
    title: 'El arte de amar',
    author: 'Erich Fromm',
    year: 1956,
    genre: 'Psicología / Filosofía',
    tagline: 'El amor no es un sentimiento sino una habilidad que se aprende y practica',
    why: 'Fromm propone que el amor no es algo que nos pasa sino algo que hacemos: un arte que requiere conocimiento y esfuerzo, como cualquier otro. Para quien trabaja en bienestar emocional, este libro reencuadra la conexión humana como práctica activa.',
    open_library_key: null,
  },
  {
    id: 26,
    emoji: '🌿',
    title: 'Walden',
    author: 'Henry David Thoreau',
    year: 1854,
    genre: 'Literatura / Filosofía',
    tagline: 'Dos años de vida deliberada y simple en los bosques de Concord',
    why: 'Thoreau se fue al bosque para "vivir deliberadamente, para mamar la médula de la vida". Su experimento de simplicidad radical es una invitación a preguntarse qué es realmente esencial y qué es meramente costumbre acumulada.',
    open_library_key: null,
  },
  {
    id: 27,
    emoji: '🎵',
    title: 'Poeta en Nueva York',
    author: 'Federico García Lorca',
    year: 1940,
    genre: 'Poesía',
    tagline: 'El duelo poético más intenso frente a la deshumanización moderna',
    why: 'Lorca escribió estos poemas en el dolor de su extranjería en Nueva York, frente a una modernidad que lo angustiaba. La poesía como forma de procesar la adversidad y mantener la sensibilidad humana es una de las disciplinas más olvidadas.',
    open_library_key: null,
  },
  {
    id: 28,
    emoji: '🏋️',
    title: 'La disciplina de la libertad',
    author: 'Jocko Willink',
    year: 2017,
    genre: 'Liderazgo / Autodesarrollo',
    tagline: 'La disciplina es el camino hacia la libertad real',
    why: 'Excomandante de los Navy SEAL, Willink tiene un mensaje simple y poderoso: la disciplina no restringe la libertad, la genera. Para quien trabaja en construir rutinas y hábitos exigentes, este libro ofrece la filosofía detrás del sacrificio.',
    open_library_key: null,
  },
]

// ── Respuestas de estado de ánimo ─────────────────────────────────────────────

export const MOOD_RESPONSES = {
  1: {
    type: 'support',
    title: 'Hoy es un día difícil',
    message: 'Sentirse así es completamente humano, {name}. No hay nada roto en ti. Los días bajos no son señal de debilidad ni de fracaso: son parte del ritmo natural de cualquier ser humano que vive con intensidad. Reconocer cómo te sientes, en lugar de ignorarlo, ya es un acto de valentía.',
    quote: {
      text: 'Cuando ya no podemos cambiar una situación, nos enfrentamos al desafío de cambiarnos a nosotros mismos.',
      author: 'Viktor Frankl',
    },
    actions: [
      'Respiración 4-7-8: inhala 4 segundos, retén 7, exhala lentamente durante 8. Repite 4 veces.',
      'Sal a caminar 10 minutos sin teléfono. No es evasión: el movimiento físico reduce el cortisol hasta un 15%.',
      'Escribe 3 cosas pequeñas que están presentes hoy, aunque sean mínimas: una taza de café caliente, que amaneciste.',
    ],
    affirmation: 'El descanso también es disciplina. Cuidarte hoy es prepararte para mañana.',
  },
  2: {
    type: 'support',
    title: 'Hoy el peso se siente más',
    message: 'Cuando el día se siente gris, {name}, no necesitas forzarte a estar bien. Lo que sientes tiene valor y merece ser reconocido, no apurado. La tristeza, cuando se le permite fluir sin resistencia excesiva, tiene una función: procesa lo que aún está pendiente de integrar.',
    quote: {
      text: 'La herida es el lugar por donde entra la luz.',
      author: 'Rumi',
    },
    actions: [
      'Date permiso explícito de no estar bien hoy. No como excusa, sino como acto de autocompasión.',
      'Ponte en contacto con alguien que te haga sentir visto: un mensaje corto, una llamada breve.',
      'Escribe sin censura durante 5 minutos lo que estás sintiendo. No necesitas mostrárselo a nadie.',
    ],
    affirmation: 'No tienes que ganarte el derecho a sentirte mal. Sentir es parte de estar vivo.',
  },
  3: {
    type: 'neutral',
    title: 'Un día en punto neutro',
    message: 'No todo los días son de alta energía, {name}, y eso está perfectamente bien. Los días neutros son el terreno fértil donde se consolida lo que se ha trabajado. La constancia no siempre se siente inspiradora; a veces solo es moverse.',
    quote: {
      text: 'No busques que los eventos ocurran como deseas, sino desea que los eventos ocurran como son, y serás feliz.',
      author: 'Epicteto',
    },
    tip: 'En los días neutros, una sola acción pequeña y concreta puede ser suficiente para generar momentum. Elige una.',
  },
  4: {
    type: 'celebrate',
    title: '¡Hoy tienes energía!',
    message: 'Ese estado que sientes ahora, {name}, es energía real. No lo desperdicies en distracciones: canalízalo hacia lo que más importa. Los días buenos son los días en que se construye; los días difíciles son los que se sostiene. Hoy toca construir.',
    quote: {
      text: 'No hay secretos para el éxito. Es el resultado de la preparación, el trabajo duro y el aprendizaje del fracaso.',
      author: 'Colin Powell',
    },
    cta: 'Aprovecha esta energía en tu entrenamiento y en la tarea más importante del día.',
  },
  5: {
    type: 'celebrate',
    title: '¡Estás en tu mejor momento!',
    message: 'Días como este, {name}, son los que recuerdas. La energía que sientes es el resultado acumulado de todo lo que has construido: cada entrenamiento, cada hábito, cada vez que elegiste la disciplina sobre la comodidad. Hoy no es suerte, es consecuencia.',
    quote: {
      text: 'No es que tenga suerte. Es que cuando llega la oportunidad, estoy preparado.',
      author: 'Séneca',
    },
    cta: '¡Establece un récord personal hoy! Tu cuerpo y tu mente están alineados.',
  },
}

// ── Citas de respaldo (20) ────────────────────────────────────────────────────

export const FALLBACK_QUOTES = [
  { text: 'No busques que los eventos ocurran como deseas, sino desea que los eventos ocurran como son, y serás feliz.', author: 'Epicteto' },
  { text: 'La vida que no se examina no merece ser vivida.', author: 'Sócrates' },
  { text: 'El mayor obstáculo para vivir es la expectativa, que depende del mañana y pierde hoy.', author: 'Séneca' },
  { text: 'No es el hombre que tiene poco quien es pobre, sino el que desea más.', author: 'Séneca' },
  { text: 'Cuando ya no podemos cambiar una situación, nos enfrentamos al desafío de cambiarnos a nosotros mismos.', author: 'Viktor Frankl' },
  { text: 'La herida es el lugar por donde entra la luz.', author: 'Rumi' },
  { text: 'Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre.', author: 'Mahatma Gandhi' },
  { text: 'El dolor es inevitable, el sufrimiento es opcional.', author: 'Haruki Murakami' },
  { text: 'En la mente del principiante hay muchas posibilidades, pero en la mente del experto hay pocas.', author: 'Shunryu Suzuki' },
  { text: 'Conocerse a sí mismo es el comienzo de toda sabiduría.', author: 'Aristóteles' },
  { text: 'Aquel que tiene un porqué para vivir puede soportar casi cualquier cómo.', author: 'Friedrich Nietzsche' },
  { text: 'El coraje no es la ausencia del miedo, sino el juicio de que algo más importa.', author: 'Ambrose Redmoon' },
  { text: 'Cae siete veces, levántate ocho.', author: 'Proverbio japonés' },
  { text: 'Lo que no me destruye me hace más fuerte.', author: 'Friedrich Nietzsche' },
  { text: 'Quien mira afuera sueña, quien mira adentro despierta.', author: 'Carl Jung' },
  { text: 'La mayor gloria no está en nunca caer, sino en levantarse cada vez que caemos.', author: 'Confucio' },
  { text: 'Puedo controlar mis pensamientos como me place; entonces ¿quién puede interponerse en mi camino?', author: 'Marco Aurelio' },
  { text: 'La disciplina es el puente entre las metas y los logros.', author: 'Jim Rohn' },
  { text: 'Nuestros temores siempre son más numerosos que nuestros peligros.', author: 'Séneca' },
  { text: 'El cielo nunca ayuda al hombre que no quiere actuar.', author: 'Sófocles' },
]

// ── Funciones exportadas ──────────────────────────────────────────────────────

export function getTodayConcept() {
  const index = dayOfYear() % DAILY_CONCEPTS.length
  return DAILY_CONCEPTS[index]
}

export function getWeekBook() {
  const index = weekOfYear() % WEEKLY_BOOKS.length
  return WEEKLY_BOOKS[index]
}
